services:

  # Autobike development
  autobike:
    container_name: autobike_dev
    image: autobike
    hostname: bike_dev
    build:
      context: .
    stdin_open: true
    tty: true
    command: bash
    networks:
      - rosnet
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./:/usr/local/autobike

  # ROSboard
  rosboard:
    container_name: rosboard
    image: autobike
    hostname: bike_dev
    build:
      context: .
    command: bash -c "cd /usr/local/rosboard/ && ./run"
    ports:
      - 8888:8888
    networks:
      - rosnet
    depends_on:
      - autobike

   # Guacamole Server
  guacamole:
    image: guacamole/guacamole
    depends_on:
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /etc/guacamole
    ports:
      - "8080:8080"
    networks:
      - rosnet
    volumes:
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml
    platform: linux/amd64

  # Guacamole Proxy Daemon
  guacd:
    image: guacamole/guacd
    networks:
      - rosnet
    platform: linux/amd64


networks:
  rosnet:
