version: '3'
services:

  # Autobike development
  autobike:
    container_name: autobike_dev
    image: autobike:tk
    hostname: bike_dev
    build:
      context: .
    command: bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - rosnet
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./:/usr/app

  # ROSboard
  rosboard:
    container_name: rosboard
    image: autobike:tk
    hostname: bike_dev
    build:
      context: .
    command: bash -c "cd /usr/app/rosboard && ./run"
    ports:
      - "8888:8888"
    networks:
      - rosnet
    depends_on:
      - autobike

networks:
  rosnet:
