services:

  # Autobike development
  autobike:
    container_name: autobike_dev
    platform: linux/amd64
    image: autobike
    hostname: bike_dev
    build:
      context: .
    stdin_open: true
    tty: true
    command: bash
    networks:
      - x11
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    volumes:
      - ./:/usr/local/autobike

  # NoVNC for x11 apps
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
