name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # We only need to test on one OS as we are using Docker
    runs-on: ubuntu-latest

    steps:
      # Checkout  code
      - name: Checkout code
        uses: actions/checkout@v3

        # Build Docker image
      - name: Build Docker image
        run: docker build -t autobike:workflow .

      # Run Black formatting check
      - name: Black formatting check
        run: docker run --rm autobike:workflow black --check --config pyproject.toml .

      # Run Pylint linting
      - name: Pylint linting
        run: docker run --rm autobike:workflow pylint --rcfile=pyproject.toml src/

      # Run Pytest with code coverage
      - name: Pytest with code coverage
        run: docker run --rm autobike:workflow pytest --cov=./ --cov-report=xml

      # Upload to codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
